name: Rulers Tests
on: [push]

jobs:
  rulers-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0
      - name: Install dependencies
        working-directory: rulers
        run: bundle install
      - name: Run tests
        working-directory: rulers
        run: ruby test/application_test.rb
